server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agri_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    org.hibernate.SQL: DEBUG